program: train_wandb.py
project: Exp5-gcn_bases
entity: aida_dti
name: lower_gcn_bases
method: grid
metric:
  name: val_auc
  goal: maximize
  target: 0.95
parameters:
  experiment_name: 
    value: last_epoch_test
  gpu:
    value: 1
  num_gcn_layers:
    values: [1, 2, 3,] #[3, 5]  # [3,5,11]
  num_bases:
    values: [2, 3, 4, 5, 6] # [4, 16] # [4,16,256]
  rel_emb_dim:
    values: [8] # [4,8,32] # 16은 기존 값
  attn_rel_emb_dim:
    values: [8] # [4,8,32]
  emb_dim:
    values: [8] # [4,8,32]
  lr:
    values: [2e-5] #[1e-5, 2e-5] # values: 
  hop:
    values: [4] # values: [2, l4]
  batch_size:
    value: 128  # values: [ 64, 128]
  dropout:
    values: [0.3] # [0.3, 0.5, 0.7]
  edge_dropout:
    values: [0.2] # [0.2, 0.4, 0.6, 0.8]
  num_epochs:
    value: 500 # values: [500]
  
  dataset:
    value: vec
  train_file:
    value: train
  valid_file:
    value: dev
  test_file:
    value: test
  protein_embedding_replace:
    value: True
  protein_embedding_method:
    values: ['prot_bert'] # ['prot_t5_xl_bfd', 'prot_bert_bfd', 'prot_t5_xl_uniref50', 'prostt5', 'prot_bert', 'prot_bert_average'] 
  drug_embedding_method:
    values: ['morgan'] # ['map4', 'morgan']
  feat_dim:
    value: 1024
  pfeat_dim:
    value: 1024